'use strict';
/**
 * Billing module upload helper.
 * Exports:
 *   billingUpload  — multer-S3 middleware for form file uploads
 *   uploadBufferToS3 — programmatic S3 upload for PDF buffers
 */
const multer = require('multer');
const multerS3 = require('multer-s3');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const path = require('path');
require('dotenv').config();

const BUCKET = process.env.AWS_BUCKET_NAME || process.env.AWS_S3_BUCKET_NAME;
const REGION = process.env.AWS_REGION || 'ap-south-1';

const s3Client = new S3Client({
  region: REGION,
  ...(process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY
    ? {
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        },
      }
    : {}),
});

// ── Multer-S3 storage (procurement bill photos) ─────────────────────────────
const billingStorage = multerS3({
  s3: s3Client,
  bucket: BUCKET,
  metadata: (req, file, cb) => cb(null, { fieldName: file.fieldname }),
  key: (req, file, cb) => {
    const unique = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
    cb(null, `billing-uploads/packing/${unique}${path.extname(file.originalname)}`);
  },
});

const fileFilter = (req, file, cb) => {
  const allowed = ['.jpg', '.jpeg', '.png', '.webp', '.heic', '.heif'];
  if (allowed.includes(path.extname(file.originalname).toLowerCase())) {
    cb(null, true);
  } else {
    cb(new Error('Only image files are allowed for bill uploads'), false);
  }
};

/** Multer middleware for form-based image uploads */
const billingUpload = multer({
  storage: billingStorage,
  fileFilter,
  limits: { fileSize: 25 * 1024 * 1024 }, // 25 MB
});

// ── Programmatic S3 upload (for PDFs generated by billing.pdf.js) ────────────
/**
 * Upload a Buffer to S3 and return its public URL.
 * @param {Buffer} buffer - File content
 * @param {string} key - S3 object key (path inside bucket)
 * @param {string} contentType - MIME type
 * @returns {Promise<string>} Public S3 URL
 */
const uploadBufferToS3 = async (buffer, key, contentType) => {
  const cmd = new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    Body: buffer,
    ContentType: contentType,
  });
  await s3Client.send(cmd);
  return `https://${BUCKET}.s3.${REGION}.amazonaws.com/${key}`;
};

module.exports = { billingUpload, uploadBufferToS3 };
